name: testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.10.0+1  # Perbarui ke versi terbaru yang kompatibel
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image: ^3.0.1
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/facenet.tflite

